name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ruby & Bundler
        run: |
          sudo apt update
          sudo apt install -y ruby-full build-essential zlib1g-dev
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          gem install bundler

      - name: Install Jekyll Dependencies
        run: |
          export PATH="$HOME/gems/bin:$PATH"
          bundle install

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Disable Jekyll Processing for Static Files
        run: touch .nojekyll

      - name: Build with Jekyll
        run: |
          export PATH="$HOME/gems/bin:$PATH"
          JEKYLL_ENV=production bundle exec jekyll build --trace --destination ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
